[package]
name = "thorvg_tester"
version = "0.1.0"
edition = "2021"
authors = ["Rafał Mikrut"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image_hasher = "1.0.0"
image="0.24.3"
bk-tree = "0.4.0"
hamming = "0.1.3"
rayon = "1.5.3"
walkdir = "2.3.2"