name: Rust

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Store Linux
        uses: actions/upload-artifact@v3
        with:
          name: svg_tester
          path: target/release/svg_tester

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install things
        run: |
          sudo apt install -y wget2 librsvg2-dev librsvg2-bin ninja-build git gcc-multilib g++-multilib
          sudo pip3 install meson
      - name: Compile Thorvg
        run: |
          git clone https://github.com/thorvg/thorvg.git
          cd thorvg
          meson . build -Dtools=svg2png
          sudo ninja -C build install
          cd ..
      - name: Build
        run: cargo build --release
      - name: Prepare tests
        run: |
          wget https://github.com/qarmin/SVG-regression-finder/releases/download/0.1.0/SVG2BigPack.zip
          unzip SVG2BigPack.zip
          mv ci_settings.toml settings.toml
          mkdir BrokenSVG
      - name: Run tests
        run: |
          target/release/svg_tester
      - name: Store Broken Images
        uses: actions/upload-artifact@v3
        with:
          name: broken-images
          path: BrokenSVG

  test_sanitizer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install things
        run: |
          sudo apt install -y wget2 librsvg2-dev librsvg2-bin ninja-build git gcc-multilib g++-multilib
          sudo pip3 install meson
      - name: Compile Thorvg
        run: |
          git clone https://github.com/thorvg/thorvg.git
          cd thorvg
          meson . build -Dtools=svg2png -Db_sanitize=address,undefined
          sudo ninja -C build install
          cd ..
      - name: Build
        run: cargo build --release
      - name: Prepare tests
        run: |
          wget https://github.com/qarmin/SVG-regression-finder/releases/download/0.1.0/SVG2BigPack.zip
          unzip SVG2BigPack.zip
          mv ci_settings.toml settings.toml
          mkdir BrokenSVG
      - name: Run tests
        run: |
          target/release/svg_tester