name: 🐧 Linux
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-default:
    strategy:
      matrix:
        toolchain: [ stable ]
        type: [ release ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            target
          key: linux-default-${{github.ref}}-${{github.sha}}
          restore-keys: |
            linux-default-${{github.ref}}-${{github.sha}}

      - name: Build Release
        run: cargo build --release
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0"

      - name: Store Linux
        uses: actions/upload-artifact@v2
        with:
          name: thorvg_tester-${{ runner.os }}-${{ matrix.toolchain }}
          path: target/release/thorvg_tester