name: Thorvg Normal Regression

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install things
        run: |
          sudo apt install -y wget2 librsvg2-dev librsvg2-bin ninja-build git gcc-multilib g++-multilib
          sudo pip3 install meson

      - name: Compile Thorvg
        run: |
          git clone https://github.com/thorvg/thorvg.git
          cd thorvg
          meson . build -Dtools=svg2png
          sudo ninja -C build install
          cd ..

      - name: Build
        run: cargo build --release

      - name: Prepare tests
        run: |
          wget https://github.com/thorvg/thorvg/files/11356766/AA_5.svg.zip
          unzip AA_5.svg.zip

      - name: Run tests
        run: |
          cp misc/same_results.py same_results.py
          python3 same_results.py AA_5.svg ./thorvg/build/src/bin/svg2png/svg2png 400 1000

      - name: Store Thorvg
        uses: actions/upload-artifact@v3
        with:
          name: thorvg-binaries
          path: "./thorvg/build/src/"
          if-no-files-found: ignore