name: Thorvg Rsvg Normal

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install things
        run: |
          sudo apt install -y wget2 librsvg2-dev librsvg2-bin ninja-build git gcc-multilib g++-multilib
          sudo pip3 install meson

      - name: Compile Thorvg
        run: |
          git clone https://github.com/thorvg/thorvg.git
          cd thorvg
          meson . build -Dtools=svg2png
          sudo ninja -C build install
          cd ..

      - name: Build
        run: cargo build --release

      - name: Prepare tests
        run: |
          wget https://github.com/qarmin/SVG-regression-finder/releases/download/0.2.0/SVG5BigPack.zip
          unzip SVG5BigPack.zip
          mv misc/ci_settings.toml settings.toml

      - name: Run tests
        run: |
          target/release/svg_tester

      - name: Store Ignored Images
        uses: actions/upload-artifact@v3
        with:
          name: ignored-images
          path: IgnoredSVG
          if-no-files-found: ignore

      - name: Store Broken Images
        uses: actions/upload-artifact@v3
        with:
          name: broken-images
          path: BrokenSVG
          if-no-files-found: ignore

      - name: Store Problematic Images
        uses: actions/upload-artifact@v3
        with:
          name: problematic-images
          path: ProblematicSVG
          if-no-files-found: ignore